'use client';

import { useEffect } from 'react';
import PageHeader from '@/components/PageHeader';
import Section from '@/components/Section';

const sections = [
  {
    title: 'Acceptance of Terms',
    content:
      'By accessing or using VoyageAI, you agree to these Terms of Service. If you do not agree, please do not use our platform. We reserve the right to update these terms, and continued use after changes constitutes acceptance.',
  },
  {
    title: 'Description of Service',
    content:
      'VoyageAI provides AI-powered travel planning tools including personalized itinerary generation, destination recommendations, budget planning, and a conversational travel assistant. Our service is provided "as is" and may be modified or discontinued at any time.',
  },
  {
    title: 'User Accounts',
    content:
      'You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. You must provide accurate information during registration and keep it up to date. One person may not maintain more than one account.',
  },
  {
    title: 'Acceptable Use',
    content:
      'You agree not to misuse VoyageAI: do not attempt to access other users\' accounts, do not use the service for illegal purposes, do not attempt to reverse-engineer or exploit our AI models, do not upload malicious content, and do not interfere with the platform\'s operation.',
  },
  {
    title: 'AI-Generated Content',
    content:
      'Travel itineraries, recommendations, and other content generated by our AI are suggestions only. They may contain inaccuracies or outdated information. You are responsible for verifying all travel details including prices, availability, visa requirements, and safety conditions before traveling.',
  },
  {
    title: 'Intellectual Property',
    content:
      'VoyageAI and its original content, features, and functionality are owned by VoyageAI, Inc. and are protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, or reverse-engineer any part of our service.',
  },
  {
    title: 'User Content',
    content:
      'By submitting content to VoyageAI (reviews, trip details, messages), you grant us a non-exclusive license to use, store, and display that content to provide and improve our service. You retain ownership of your content.',
  },
  {
    title: 'Limitation of Liability',
    content:
      'VoyageAI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service. Our total liability shall not exceed the amount you paid us in the twelve months preceding the claim.',
  },
  {
    title: 'Termination',
    content:
      'We may suspend or terminate your account at any time for violation of these terms. You may also delete your account at any time through your settings. Upon termination, your right to use the service ceases immediately.',
  },
  {
    title: 'Governing Law',
    content:
      'These terms are governed by the laws of the State of California, United States, without regard to conflict of law principles. Any disputes shall be resolved in the courts of San Francisco County, California.',
  },
  {
    title: 'Contact',
    content:
      'Questions about these Terms? Contact us at legal@voyageai.com.',
  },
];

export default function TermsPage() {
  useEffect(() => {
    document.title = 'Terms of Service | VoyageAI';
  }, []);

  return (
    <div className="min-h-screen bg-slate-50">
      <PageHeader
        title="Terms of Service"
        description="The rules and guidelines for using VoyageAI."
      />

      <Section bgColor="white" padding="default">
        <div className="max-w-3xl mx-auto">
          <p className="text-body-sm text-slate-400 mb-8">
            Last updated: December 2024
          </p>
          <p className="text-body-lg text-slate-600 mb-8">
            These Terms of Service govern your use of VoyageAI&apos;s AI-powered
            travel planning platform. Please read them carefully.
          </p>

          <div className="space-y-8">
            {sections.map((section) => (
              <div key={section.title}>
                <h2 className="text-h4 text-slate-900 mb-3">
                  {section.title}
                </h2>
                <p className="text-body text-slate-600 leading-relaxed">
                  {section.content}
                </p>
              </div>
            ))}
          </div>
        </div>
      </Section>
    </div>
  );
}
